### ISSUE TITLE
[ 7장 ] 업그레이드 아이디어 관련 질문드립니다.

### ISSUE THREAD

**Issue by cabbage556** [wapj/jsbackend#1]
안녕하세요. 좋은 책 써주셔서 기쁜 마음으로 잘 공부하고 있습니다.

현재 7장 업그레이드 아이디어를 진행 중인데 업그레이드 아이디어 코드를 따로 주시는 건 아니신가요?

구현 중에 혹시 코드를 제공하시나 싶어서 질문드립니다.

감사합니다.

**Comment by andy-sg** [comment]
모든 코드를 제공하지는 않습니다. 
tailwindcss의 경우에는 아래 링크에서 확인해 보실 수 있습니다! 
감사합니다~ 

https://github.com/wapj/jsbackend/tree/main/chapter7/board-tailwind

**Comment by cabbage556** [comment]
감사합니다.
