### ISSUE TITLE
교재에서 detail 기능 생성시 

### ISSUE THREAD

**Issue by fecu89** [wapj/jsbackend#10]
app.get("/detail/:id", async (req, res) => {
    const result = await postService.getDetailPost(collection, req.params.id);
    console.log(result);
    res.render("detail", {
        title : "테스트 게시판",
        post : result. value,  ==> 이 부분을 result로 하니 정상출력되네요^^
    });
});

**Comment by andy-sg** [comment]
이건 질문이 아니신듯하니... 닫을게요..^^;

**Comment by wapj** [comment]
질문하시려다 답을 하신듯하여... 닫겠습니다..^^;
