### ISSUE TITLE
8.4.5 메서드 시그니처가 변경되어서 수정해야 하는 부분

### ISSUE THREAD

**Issue by wjdtngus9536** [wapj/jsbackend#11]
안녕하세요 저자님
328p에 컨트롤러 getAllPosts 메서드도 서비스에서 비동기로 변경되었는데 비동기를 지원하는 메서드로 시그니처 변경을 하지 않아도 되는 이유가 궁금합니다.

**Comment by wapj** [comment]
NestJS에서 응답을 내려줄때 Promise(비동기)를 자동으로 처리해줍니다. 

제가 테스트 코드를 추가해놨으니 한번 확인해보세요~ 
https://github.com/wapj/jsbackend/commit/742bae659d9a32bf6762f81b96a04bff3d2f31da
