### ISSUE TITLE
Node.js 백엔드 개발자 되기 책 관련 질문 있습니다

### ISSUE THREAD

**Issue by kdream95** [wapj/jsbackend#12]
박승규 님 안녕하세요

책 너무 잘 보고 있구요 
예제 코드와 꼼꼼한 설명 모두 좋습니다
책을 보다가 '이거 뭐지?' 라고 궁금한 게 있으면 뒤에 신기하게도 설명을 해주시더라구요^^

현재 10장까지 다 봤는데요
10장 예제에서 궁금한 게 있어서 글을 올립니다

@Controller('auth')
export class AuthController {
  ... 생략
  @UseGuards(AuthenticatedGuard)
  @Get('test-guard2')
  testGuardWithSession(@Request() req) {
    return req.user;
  }
}

위 코드에서 req.user  이 부분이 궁금한데요..
미들웨어(?)에서 세션을 읽어 request 객체의 'user' 속성으로 값을 넣어주는 거 같은데..
( SessionSerializer 의 deserializeUser 메소드가 핸들러 전에 호출 되는 것은 로그를 찍어 확인해 봤구요 )
main.ts 에서  app.use(passport.session());  이 코드가 이 기능을 활성화 해 주는 건가요?
세션과 관련하여 자세한 흐름과 설명 부탁드립니다

그리고 10장 퀴즈를 보면 '파이프' 와 '가드' 모두 '미들웨어' 라고 표현한 부분이 있는데요
실제 내부적으로도 '파이프' 와 '가드' 가 모두 '미들웨어' 의 한 종류인가요? ( 부모 클래스가 같은지.. )

회신 기다리겠습니다.

**Comment by andy-sg** [comment]
질문이 정확하게 뭔지 잘 모르겠습니다만, 제 나름대로 답변드리겠습니다. 

## request 속성에 user를 넣어주는 곳이 어디인가? 
canActivate 함수에서 넣어줍니다. 
https://github.com/nestjs/passport/blob/09de296d85b573773b61b4b438b98181838c64c0/lib/auth.guard.ts#L73

예제에서는 canActivate 함수는 LocalAuthGuard에 있습니다. 

## 세션과 관련하여 자세한 흐름을 알려주세요. 
로그인 부터 세션까지대한 흐름과 설명은 책에 있습니다. 해당 부분 확인해보시는게 좋을것 같습니다. 
<img width="669" alt="image" src="https://github.com/wapj/jsbackend/assets/100417931/b919dcbf-2f36-475b-a35e-ccf7e3a30087">

## 파이프랑 가드가 미들웨어인가? 
미들웨어 이기도 하고 아니기도 합니다. 
미들웨어는 요청과 응답사이에 추가적인 작업을 한다는 개념에서 보면 미들웨어가 맞습니다. 
다만 NestJS 코드에서 같은 부모를 상속받지는 않아요. 
엄격하게 구분을 하기 위해서 NestJS사용시에는 구분해서 부르는것이 좋습니다. 

도움이 돼셨으면 좋겠습니다.

**Comment by kdream95** [comment]
답변 감사합니다~
근데..  /auth/login3 핸들러를 통해 정상적으로 로그인 처리 및 세션 저장 후 
바로 /auth/test-guard2  를 호출 할 때 AuthenticatedGuard 의 canActivate 호출 전에 
세션에서 데이터를 가져와 request 객체에 user 속성 값을 넣어주는 같아서요..
이 부분이 궁금합니다~^^

**Comment by kdream95** [comment]
친절한 답변 감사드립니다^^
