### ISSUE TITLE
chapter7 상세페이지 업로드 불가능 문제 

### ISSUE THREAD

**Issue by Dec32th** [wapj/jsbackend#13]
---
name: 책 관련 질문
title: "[chapter7] 질문 "
labels: book-question
---
** 페이지 ** 
p.273의 상세 페이지가 구현이 되지 않습니다. 
(p.252-273까지의 내용을 바탕으로 구현하였습니다.)

** 질문 ** 
Mongodb로 상세페이지의 내용과 제목, 작성자와 같은 부분이 전달이 잘 되었음을 확인하였습니다. (mongodb compass를 이용하여 제대로 전달되었음을 확인하였습니다.) 왜 상세페이지가 제대로 보이지 않는지를 모르겠습니다.
아래 순서대로 detail.handlebar 과 app.js 코드입니다. (issue를 써 보는게 처음이라 코드를 정확히 어떻게 첨부해야하는지 모르겠습니다. 죄송합니다.  )

```
<h1>{{title}}</h1>
{{#with post}}
<h2 class ="text-xl">{{title}}</h2>
{{!-- 게시글의 제목 --}}
<div>
    작성자 : <b>{{writer}}</b>
</div>
<div>
    조회수 : {{hits}} | 작성일시 : {{dateString createdDt}}
    {{!-- 조회수와 작성일시 --}}
    <button onclick = "modifyPost()">수정</button>
    <button onclick = "deletePost()">삭제</button>
    {{!-- 게시글 관련 버튼 영역 --}}
</div>

<div>
    <pre>{{content}}</pre>
    {{!-- 본문 표시 영역 --}}
</div>

<section>
    <div>
        <h3>3개의 댓글이 있습니다. </h3>
    </div>
    <form method = "post" action="/write-comment">
        <div>
            <div>
                <input type="text" name ="name" placeholder="이름" />
                <input type="password" name ="password" placeholder="비밀번호" />
            </div>
            <div>
                <textarea cols ="40" rows = "3" name="comment" placeholder="댓글을 입력해주세요"></textarea>
                <br/>
                <br/>
                <button>댓글 쓰기</button>
            </div>
            {{!-- 댓글 전송 버튼 --}}
        </div>
    </form>
</section>

{{!-- 댓글 표시 영역 --}}
<section>
    <div>
        <div>
            작성자 : <b>댓글 작성자</b>
        </div>
        <div>
            작성일시 : 2022-01-01 00:00:00
            <button onclick ="deleteComment('1')">삭제</button>
        </div>
    </div>
    <div>
        <pre>{{comment}}</pre>
    </div>
</section>

{{/with}}
<footer>
    <div>
        <a href="/">목록으로</a>
    </div>
</footer>
<script>
    async function modifyPost() { }
    async function deletePost() { }
</script>

```

app.js
```
const express = require("express");
const handlebars = require("express-handlebars");
const postService = require("./services/post-service");         // 10. 서비스 파일 로딩

const app = express();
// 9. req.body와 POST요청을 해석하기 위한 설정
app.use(express.json());
app.use(express.urlencoded({extended:true}));

// 5. 몽고디비 연결 함수 
const mongodbConnection = require("./configs/mongodb-connection");

app.engine(
    "handlebars",
    handlebars.create({                             // 8. 핸들바 생성 및 엔진 반환 
        helpers: require("./configs/handlebars-helpers"),
    }).engine,
);                                                  // 1. 템플릿 엔진으로 핸들바 등록
app.set("view engine", "handlebars");               // 2. 웹페이지 로드 시 사용할 테플릿 엔진 설정 
app.set("views", __dirname + "/views");             // 3. 뷰 디렉터리를 views로 설정

// 15. 리스트 페이지 (4. 라우터 생성 대체)
app.get("/", async (req, res) => {
    const page = parseInt(req.query.page) || 1;     // 16. 현재 페이지 데이터
    const search = req.query.search || "";          // 검색어 데이터
    try {
        // 17. postService.list에서 글 목록과 페이지네이터를 가져옴
        const [posts, paginator] = await postService.list(collection, page, search);

        // 18. 리스트 페이지 렌더링
        res.render("home", {title: "테스트 게시판", search, paginator, posts});
    } catch(error)
    {
        console.error(error);
        res.render("home", {title: "테스트 게시판"});
        // 19. 에러가 나는 경우는 빈 값으로 렌더링
    }
});

// 11. 쓰기 페이지 이동
app.get("/write", (req, res)=> {
    res.render("write", {title: "테스트 게시판"});
});

// 12. 글쓰기
app.post("/write", async(req, res) => {
    const post = req.body;
    // 13. 글쓰기 후 결과 반환
    const result = await postService.writePost(collection, post);
    // 14. 생성된 도큐먼트의 _id를 사용해 상세페이지로 이동
    res.redirect(`/detail/${result.insertedId}`);
});

// 상세 페이지로 이동
app.get("/detail/:id", async (req, res) => {
    // 게시글 정보 가져오기
    const result = await postService.getDetailPost(collection, req.params.id);
    res.render("detail", {
      title: "테스트 게시판",
      post: result.value,
    });
  });  

let collection;
app.listen(3000, async () => {
    console.log("Server started");
    // 6. mongodbConnection()의 결과는 mongoClient
    const mongoClient = await mongodbConnection();
    // 7. mongodbClient.db()로 데이터베이스 선택, collection()으로 컬렉션 선택 후 collection에 할당
    collection = mongoClient.db().collection("post");
    console.log("MongoDB connected");
});
```

** 스크릿 샷 (옵션) **

**Comment by wapj** [comment]
@Dec32th 안녕하세요~ 

올려주신 코드만 가지고는 원인 파악을 할 수가 없습니다. 
app.js의 상세페이지 이동에서 

```
app.get("/detail/:id", async (req, res) => {
    // 게시글 정보 가져오기
    const result = await postService.getDetailPost(collection, req.params.id);
    res.render("detail", {
      title: "테스트 게시판",
      post: result.value, 
    });
  });  
```

`result.value` 값이 무엇인지 확인이 필요한데요. 제 생각에는 여기가 null로 찍히던가 빈값으로 찍히던가 할것 같습니다. 
console.log(result.value) 를 추가하셔서 확인해보세요.

**Comment by Dec32th** [comment]
console.log(result.value);
                ^

ReferenceError: result is not defined
    at Server.<anonymous> (경로\app.js:72:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    
먼저 상세한 답변 감사드립니다!
이런 에러가 발생하면서 제대로 동작하지 않는 것 같습니다! 말씀해주신 에러가 맞는것 같은데 어떻게 해결해야하나요?

**Comment by wapj** [comment]
@Dec32th 추측이긴합니다만, 
`result` 가 null 도 아니고 undefined 인건 좀 이상한데요. 
postService.getDetailPost 함수의 구현이 잘 못되었을 가능성이 클것 같습니다. 
postService.getDetailPost 함수를 한번 살펴보시고, 그래도 원인을 못찾으시면 관련해서 전체 코드를 올려주세요. 

프로젝트 전체 파일을 압축해서 올리는 것도 방법일 것 같습니다.

**Comment by Dec32th** [comment]
ObjectedID 부분에서 TypeError: Cannot read properties of undefined (reading 'find') at Object.list 라는 에러가 발생해서 ObjectedID(ID) 부분을 수정했었는데...그 부분에서 문제가 생긴 것 같습니다. 현재 그 부분은 위의 TypeError가 다시 발생하는 상태입니다. 

아래에 프로젝트 전체 파일을 압축해서 올렸습니다. 
[chapter7.zip](https://github.com/user-attachments/files/16369503/chapter7.zip)

**Comment by wapj** [comment]
확인해보니  `mongodb-connection.js` 에 있는 uri 주소로 접속을 못하고 있습니다.

mongodb가 잘 떠 있는지, 확인해보시는게 좋을 것 같아요.

const {MongoClient} = require("mongodb");
// 1. 몽고디비 연결 주소
const uri= ***@***.***/"


module.exports = function(callback) { // 2. 몽고디비 커넥션 연결 함수 반환
return MongoClient.connect(uri, callback);
};

2024년 7월 25일 (목) 오전 11:34, hyekyeong won ***@***.***>님이 작성:

**Comment by Dec32th** [comment]
대답 감사합니다.
계속 mongodb driver와 vscode를 이용해서 연결을 시도해 보았으나, reference 에러가 발생하면서 result의 값이 정의되지 않았다는 에러가 계속 발생합니다...console.log로 result.value를 한 부분에서 에러가 발생한다고 하고 mongodb의 connect를 이용해서 하였는데도 제대로 연결이 되지 않는 것 같습니다.
양식의 문제인지 문자열 양식을 바꿔보았으나 여전히 동일한 에러가 발생합니다..

**Comment by wapj** [comment]
MongoDB 가 정상적으로 작동하고 있는지 먼저 확인해보세요~ 제생각에 코드 문제는 아닌것 같아요 7/29/24 오후 9:52, hyekyeong won ***@***.***> 작성:﻿
대답 감사합니다.
계속 mongodb driver와 vscode를 이용해서 연결을 시도해 보았으나, reference 에러가 발생하면서 result의 값이 정의되지 않았다는 에러가 계속 발생합니다...console.log로 result.value를 한 부분에서 에러가 발생한다고 하고 mongodb의 connect를 이용해서 하였는데도 제대로 연결이 되지 않는 것 같습니다.
양식의 문제인지 문자열 양식을 바꿔보았으나 여전히 동일한 에러가 발생합니다..

**Comment by wapj** [comment]
mongodb가 활성화 되지 않는 문제로 보여서 일단 닫습니다.
