### ISSUE TITLE
[챕터 10] p.396 오탈자 신고

### ISSUE THREAD

**Issue by MainFe** [wapj/jsbackend#14]
---
name: 책 관련 질문
title: "[챕터] 질문 "
labels: book-question
---
** 페이지 ** 
p.396 페이지의 소스코드 이미지 입니다.

** 질문 ** 
service가 serivice로 오타가난거 같아 신고합니다.
코드 상으로는 문제가 없지만, 오탈자도 중요하니까영

** 스크릿 샷 (옵션) **
![image](https://github.com/user-attachments/assets/85e112d5-432b-40a8-ae42-c605e899074c)

**Comment by wapj** [comment]
감사합니다~ 
오탈자 기록 구글 시트에 추가해두었습니다! 
https://docs.google.com/spreadsheets/d/16HE9A2Sj8FKlxHwSjv_X3Xd4NnEyqIWeHEzzvctIbNA/edit?gid=0#gid=0
