### ISSUE TITLE
[챕터10] 질문입니다

### ISSUE THREAD

**Issue by quartzs2** [wapj/jsbackend#15]
---
name: 책 관련 질문
title: "[챕터] 질문 "
labels: book-question
---
** 페이지 ** 
[10.5] 407p~408p

** 오타 ** 
오탈자입니다.
7일인데 1day로 표기되어 있어서 표시했습니다.  login함수에서는 
 스샷과 동일하게 7일로 설정되어 있는데, 주석과 409p에서는 쿠키 만료시간을 '하루'로 표기하라고 나와있습니다. 
![화면 캡처 2024-09-07 230845](https://github.com/user-attachments/assets/36a1e117-b5d6-410a-b7ed-e1559158567a)

** 질문 ** 
책에서처럼 auth.http를 사용하지 않고, postman으로 테스트를 하고 있는데요

408p에서 login을 실행하고 그뒤에 login2를 실행하는데, 
login2의 if (!req.cookies['login'] && req.user) 부분에서 !req.cookies['login'] 를 만족시키지 못해서 책에 나오는 코드를 그대로 사용했을 때 가드 테스트가 제대로 이뤄지지 않는 것 같습니다.  (login2를 실행해도 login에서의 expires시간이 유지됩니다. )

그래서 login2를 다음과 같이 바꾸고 진행했습니다.

![화면 캡처 2024-09-07 231740](https://github.com/user-attachments/assets/c3147017-6c9c-4d6b-b9ae-22957523e80e)

login2를 바꿔서 사용했을 시 책에서 의도한 대로 동작합니다. 

그런데  아래 사진처럼 json 데이터를 같이 보냈을 경우에도 403 에러가 뜨지 않고 '로그인했을 때만 보이는 메시지입니다.' 응답을 받습니다. 왜 이런 결과가 나오는지 궁금합니다. (json데이터를 보내지 않고 none으로 설정하면 403 에러가 정상적으로 뜹니다)
++ 데이터베이스 mysql쓰고있습니다. postman이랑 mysql사용한것, login2코드 수정한것 빼고는 책이랑 동일한 코드입니다.
![화면 캡처 2024-09-07 232131](https://github.com/user-attachments/assets/69b59f7c-da95-4548-af0b-af3f10025cc6)

**Comment by wapj** [comment]
안녕하세요~ 
오탈자 제보감사드립니다. 
말씀주신 것은 오탈자 정정표에 추가하였습니다. 

테스트시에 쿠키정보가 남아있다고 하셨는데요. 
유저정보를 변경해서 로그인을 시도하신것인지 궁금합니다. 

login메서드에서 쿠키생성후에 
login2 를 시도해도 이미 쿠키가 있을거라서, 유저 정보가 같다면 쿠키도 유지 될것입니다. 

예를들어 

login에서 아래 정보로 실행해서 쿠키가 생겼고, 

```
{
"email" : "test1@test.com",
"password: "1234"
}
```


login2 에서 동일한 정보로 로그인을 하신다면 
아래 if 문을 타지 않을 것이기 때문입니다. 
```
if (!req.cookies['login'] && req.user) {
```

그러므로 login 후 login2를 테스트 하시려면 유저 정보를 변경해서 테스트를 진행하셔야 합니다. 
auth.http 코드를 보시면 다음과 같이 유저정보가 다르게 되어 있습니다. 
책에도 다르게 표기하도록 추가해두겠습니다. 

```
### 로그인 
POST http://localhost:3000/auth/login
content-type: application/json

{
    "email" : "andy1@podo.com",
    "password" : "1234"
}

### 로그인 2 : LoginGuard
POST http://localhost:3000/auth/login2
content-type: application/json

{
    "email" : "andy2@podo.com",
    "password" : "1234"
}
```

**Comment by quartzs2** [comment]
GET으로 http://localhost:3000/auth/test-guard 요청을 보냈을 때, json데이터를 같이 보내면 오작동하는데 왜 그런 결과가 나오는지(에러가 떠야하는데 로그인중이라고 나오는지) 궁금합니다

**Comment by wapj** [comment]
json데이터를 같이 보낸다는 얘기는 HTTP요청의 BODY에 넣었다는 말씀이시죠? 

json 데이터를 같이 보냈을 때 로그인이 되는 것 처럼 보이는 이유는 
LoginGuard에서 HTTP 요청의 METHOD를 제한하고 있지 않기 때문입니다. 

즉 컨트롤러만 통과한다면, 
`LoginGuard` 클래스의 내부동작에서 HTTP요청이 무엇인지 판단하지는 않습니다. 
단지 body에 email, password 가 있는지 확인을 할 뿐입니다. 

```
    // ❼ 쿠키가 없으면 request의 body 정보 확인
    if (!request.body.email || !request.body.password) {
      return false;
    }
``` 

http 메서드로도 검증하는 동작을 추가하려면 
다음과 같은 코드를 추가할 수 있습니다. 
```
if (request.method !== 'POST') {
      return false;
    }
```

**Comment by quartzs2** [comment]
이해했습니다 감사합니다.
