### ISSUE TITLE
[10.6] 세션을 사용한 인증 구현 시 위변조와 탈취가 불가능하게 되는 원리를 잘 모르겠습니다.

### ISSUE THREAD

**Issue by wjdtngus9536** [wapj/jsbackend#16]
---
name: 책 관련 질문
title: "[챕터] 질문 "
labels: book-question
---
** 페이지 ** 
p.409

** 질문 ** 
안녕하십니까 저자님

1. cookies['login']에 userInfo(password 포함x)를 전부 저장하면 클라이언트 측에서 해당 쿠키 값을 요청에 포함 시켜 인증을 뚫을 수 있는 것이 문제가 되는 것이라고 생각하였습니다.
그렇다면 cookies['connect-sid']를 통해 email만 저장된다고 하더라도 해당 쿠키 값을 요청에 포함 시키게 되면 
해당 세션 아이디에 해당하는 세션 정보가 세션 저장소에 존재한다면 해당 사용자를 인증된 사용자로 판단하여 인증을 뚫을 수 있게 되는 것은 아닌가요?

2. [p. 414, 10.6.3] 세션에 정보를 저장하고 읽는 세션 시리얼라이저 구현하기에서
deserializeUser(payload, (err, payload) => void)는 이미 payload 파라미터로 email을 전달 받은 상태이고 
userInfo는 세션에서 꺼내오는 것이 아니라 getUser라는 함수를 통해 sqlite DB에서 꺼내오는 것으로 보이는데 

2-1 deserializeUser의 payload 파라미터에 email값을 전달해주는 것이 어떤 원리를 통해 이뤄지는지 잘 모르겠는데 알려주시면 감사하겠습니다.

2-2 그리고 AuthenticatedGuard에서 request.session을 확인해보면 passport: { user: 'andy@podo.com  } 과 같이 email만 들어 있던데 쿠키에 저장된 것은 sid 뿐이고 session에 저장되는 것은 email 뿐인 것인지요?

3. 책에는 10.6.7 로그인와 세션 저장 순서는 알려주시지만 인증과 세션 읽어오기, AuthenticatedGuard가 어떻게 동작하는지에 대한 설명이 없었습니다.  AuthenticatedGuard의 canActivate에서 
```
const request = context.switchToHttp().getRequest();  
console.log('request.session =', request.session);
```
만으로 session에서 정보를 읽을 수 있었는데 책의 설명에서는
request.isAuthenticated(); 를 실행할 때 세션에서 정보를 읽어서 인증 확인을 한다고 적혀있었습니다.
isAuthenticated() 실행 전에 이미 session의 정보를 읽어올 수 있다면 

3-1 request.session은 언제 어디서 쿠키의 값을 읽어 session 값을 등록 시킨 것인지
3-2 deserializeUser()는 언제 어디서 호출되는 것인지 
3-3 인증의 순서도를 대략적으로라도 알려주시면 감사하겠습니다.

**Comment by wapj** [comment]
안녕하세요~ 

1은 질문이 정확하게 뭔지 모르겠습니다만, 
대충 cookies['connect.sid']에 있는 정보를 탈취해서 쿠키에 담으면 인증을 뚫을수 있지 않느냐? 라는 질문으로 이해했습니다. 
세션정보를 정직하게 email만 담았다면, connect.sid 쿠키가 탈취될 경우 인증이 뚫릴수 있습니다. 
책에서 복잡한 예시를 들기 어렵기 때문에 email만 세션키로 활용한 것이구요. 실제로는 조금 더 복잡하게 구성을 합니다. 
쿠키에 담는 내용도 암복호화를 하여 담고, 복호화 한후에 시간, 암호화키등으로 정합성체크를 하게됩니다.

**Comment by wapj** [comment]
2-1 번 질문은 아래 이슈 확인 바랍니다. 
https://github.com/wapj/jsbackend/issues/12

2-2 
말씀주신대로 쿠키에는 세션키만 있고, 세션키를 통해서 session에 저장된 email을 찾을 수 있습니다.

**Comment by wapj** [comment]
3번은 사실 2-1과 같은 질문같은데요. 
#12 참고 바랍니다.

**Comment by wjdtngus9536** [comment]
> 3번은 사실 2-1과 같은 질문같은데요. #12 참고 바랍니다.

답변 감사합니다 다시 한 번 공부해보겠습니다.
