### ISSUE TITLE
[챕터 10] p.409 로그인2 실행 시 set-cookie가 나오지 않는 문제

### ISSUE THREAD

**Issue by fluorjo** [wapj/jsbackend#4]
안녕하세요. 책 통해 잘 공부하고 있습니다. 

챕터 10을 따라하다 보니 로그인1 까지는 잘 됐는데, 로그인 2에서 쿠키 생성이 되지 않는(?) 문제가 생겨 문의드립니다. 

main.ts 에서 import * as cookieParser from 'cookie-parser' 부분에서 cookie-parser를 읽어오지 못하는 문제가 있어 혹시 이게 원인인가 싶어서 
npm install --save-dev @types/cookie-parser 도 해보고 따로 폴더와 파일을 만들어 선언도 해봤습니다 (강사님 깃허브에는 이런 과정이 없는 것 같았습니다만) . 그래도 해결되지 않습니다. 

로그인 자체는 성공이라고 나오고 가드 테스트를 했을 때 "로그인된 때에만~"도 출력됩니다. 

도움 주시면 감사하겠습니다. 

감사합니다. 

![image](https://github.com/wapj/jsbackend/assets/82512693/9c903294-014f-4b60-baf3-5d371bdc0b7d)

https://github.com/fluorjo/flashcard_ts/commit/a7ee7a5d4c04d2972296b1323ff331e7fe1e3cc2

**Comment by andy-sg** [comment]
@fluorjo 안녕하세요~ 우선 책을 열심히 봐주셔서 감사합니다. 
제가 책관련 질문을 받기위해서 페이스북 그룹을 하나 개설 했는데요. 
여기에 질문주시면 좋을 것 같아요~ 우선 제가 올려주신 질문들은 수동으로 올려두려고 합니다. 

아래는 답변입니다. 
-----------------

책에서는 10초마다 쿠키가 삭제되도록 한다음 테스트를 하고 있는데요. 
auth/login 에서 쿠키가 7일로 설정이 되어 있습니다. 

auth/login 을 실행하여 로그인하고, 
다시 auth/login2 를 실행하면 
auth.controllers.ts 의 `login2` 메서드가 실행됩니다. 

로직을 보시면 다음과 같이 되어 있는데요. 쿠키에 login이라는게 없고, req.user가 있으면 쿠키에 값을 세팅해 주는 것입니다. 

```
if (!req.cookies["login"] && req.user) {
... 생략
}
```

그런데 auth/login 에서 이미 쿠키가 생성된 상태에서 실행을 하셨기 때문에 쿠키가 있으므로 쿠키값 세팅 로직을 타지 않는 것입니다. 
여기에 한가지 버그가 있긴합니다. 바로 누구의 쿠키인지 확인하지 않는 것인데요. 
이 부분은 추가적으로 고민해보시면 좋을 것 같습니다. 

책처럼 쿠키가 세팅되는 것을 보고 싶으시다면 auth/login API의 쿠키세팅하는 부분의 maxAge 값을 수정해보시고 하면 될 것 같습니다.
저는 6초로 세팅후 테스트하니 잘되었습니다. 

```javascript 
@Post("login")
  async login(@Request() req, @Response() res) {
    // ❶ Request, Response를 둘 다 사용
    // ❷ validateUser를 호출해 유저 정보 획득
    const userInfo = await this.authService.validateUser(
      req.body.email,
      req.body.password,
    );

    // ❸ 유저 정보가 있으면, 쿠키 정보를 Response에 저장
    if (userInfo) {
      res.cookie("login", JSON.stringify(userInfo), {
        httpOnly: false, // ❹ 브라우저에서 읽을 수 있도록 함
        maxAge: 1000 * 6, // ❺ 6초
      });
    }
    return res.send({ message: "login success" });
  }
```

답변이 되었길 바랍니다~

**Comment by wapj** [comment]
@fluorjo 안녕하세요~ 우선 책을 열심히 봐주셔서 감사합니다. 
제가 책관련 질문을 받기위해서 페이스북 그룹을 하나 개설 했는데요. 
여기에 질문주시면 좋을 것 같아요~ 우선 제가 올려주신 질문들은 수동으로 올려두려고 합니다. 

아래는 답변입니다. 
-----------------

책에서는 10초마다 쿠키가 삭제되도록 한다음 테스트를 하고 있는데요. 
auth/login 에서 쿠키가 7일로 설정이 되어 있습니다. 

auth/login 을 실행하여 로그인하고, 
다시 auth/login2 를 실행하면 
auth.controllers.ts 의 `login2` 메서드가 실행됩니다. 

로직을 보시면 다음과 같이 되어 있는데요. 쿠키에 login이라는게 없고, req.user가 있으면 쿠키에 값을 세팅해 주는 것입니다. 

```
if (!req.cookies["login"] && req.user) {
... 생략
}
```

그런데 auth/login 에서 이미 쿠키가 생성된 상태에서 실행을 하셨기 때문에 쿠키가 있으므로 쿠키값 세팅 로직을 타지 않는 것입니다. 
여기에 한가지 버그가 있긴합니다. 바로 누구의 쿠키인지 확인하지 않는 것인데요. 
이 부분은 추가적으로 고민해보시면 좋을 것 같습니다. 

책처럼 쿠키가 세팅되는 것을 보고 싶으시다면 auth/login API의 쿠키세팅하는 부분의 maxAge 값을 수정해보시고 하면 될 것 같습니다.
저는 6초로 세팅후 테스트하니 잘되었습니다. 

```javascript 
@Post("login")
  async login(@Request() req, @Response() res) {
    // ❶ Request, Response를 둘 다 사용
    // ❷ validateUser를 호출해 유저 정보 획득
    const userInfo = await this.authService.validateUser(
      req.body.email,
      req.body.password,
    );

    // ❸ 유저 정보가 있으면, 쿠키 정보를 Response에 저장
    if (userInfo) {
      res.cookie("login", JSON.stringify(userInfo), {
        httpOnly: false, // ❹ 브라우저에서 읽을 수 있도록 함
        maxAge: 1000 * 6, // ❺ 6초
      });
    }
    return res.send({ message: "login success" });
  }
```

답변이 되었길 바랍니다~

**Comment by fluorjo** [comment]
해결했습니다 감사합니다~!

**Comment by fluorjo** [comment]
> @fluorjo 안녕하세요~ 우선 책을 열심히 봐주셔서 감사합니다. 제가 책관련 질문을 받기위해서 페이스북 그룹을 하나 개설 했는데요.
> 
> [Node.js 개발자 되기](https://www.facebook.com/groups/2462290190609098)
> 
> 여기에 질문주시면 좋을 것 같아요~ 이번에 올려주신 질문은 제가 올려두겠습니다.
> 
> ## 아래는 답변입니다.
> 책에서는 10초마다 쿠키가 삭제되도록 한다음 테스트를 하고 있는데요. auth/login 에서 쿠키가 7일로 설정이 되어 있습니다.
> 
> auth/login 을 실행하여 로그인하고, 다시 auth/login2 를 실행하면 auth.controllers.ts 의 `login2` 메서드가 실행됩니다.
> 
> 로직을 보시면 다음과 같이 되어 있는데요. 쿠키에 login이라는게 없고, req.user가 있으면 쿠키에 값을 세팅해 주는 것입니다.
> 
> ```
> if (!req.cookies["login"] && req.user) {
> ... 생략
> }
> ```
> 
> 그런데 auth/login 에서 이미 쿠키가 생성된 상태에서 실행을 하셨기 때문에 쿠키가 있으므로 쿠키값 세팅 로직을 타지 않는 것입니다. 여기에 한가지 버그가 있긴합니다. 바로 누구의 쿠키인지 확인하지 않는 것인데요. 이 부분은 추가적으로 고민해보시면 좋을 것 같습니다.
> 
> 책처럼 쿠키가 세팅되는 것을 보고 싶으시다면 auth/login API의 쿠키세팅하는 부분의 maxAge 값을 수정해보시고 하면 될 것 같습니다. 저는 6초로 세팅후 테스트하니 잘되었습니다.
> 
> ```js
> @Post("login")
>   async login(@Request() req, @Response() res) {
>     // ❶ Request, Response를 둘 다 사용
>     // ❷ validateUser를 호출해 유저 정보 획득
>     const userInfo = await this.authService.validateUser(
>       req.body.email,
>       req.body.password,
>     );
> 
>     // ❸ 유저 정보가 있으면, 쿠키 정보를 Response에 저장
>     if (userInfo) {
>       res.cookie("login", JSON.stringify(userInfo), {
>         httpOnly: false, // ❹ 브라우저에서 읽을 수 있도록 함
>         maxAge: 1000 * 6, // ❺ 6초
>       });
>     }
>     return res.send({ message: "login success" });
>   }
> ```
> 
> 답변이 되었길 바랍니다~


해결했습니다 감사합니다~!
