### ISSUE TITLE
챕터 7에서의 질문 드립니다.

### ISSUE THREAD

**Issue by dbtpdnjs** [wapj/jsbackend#5]
안녕하세요.
NodeJs 실습을 하다가 궁금한 점이 있어 문의 드립니다.

챕터 7, 책 274페이지의 modifyPost() 함수 작성 시

`const result = await fetch("/check-password", {
    ...postOption,
    body: JSON.stringify({ id: "{{ post._id }}", password }),
});`

이 부분이 에서 ...postOption
문구의 ... 의 의미가 어떤 것 일까요??

postOption의 앞 ... 이 의미하는 바를 알고 싶습니다.
바쁘시겠지만 답변 부탁 드립니다.
감사합니다.

**Comment by andy-sg** [comment]
... 은 스프레드 연산자라고 불립니다. 
스프레드는 뭉쳐있는것을 펼칠때 쓰는말이죠. 

자바스크립트에서 스프레드 연산자는 
객체의 모든 속성을 다른 객체로 복사할때 주로 사용합니다. 

그런데 사용하는 형태는 객체로 뭉쳐있는 것을 
펼쳐서 넣는것처럼 보이기 때문에 스프레드 연산자라고 부르는 것 같습니다. 

이제 예제로 돌아가보겠습니다. 

예제에서 postOption코드는 다음과 같습니다. 

```javascript
const postOption = {
    method: 'POST',
    headers: {    
      'Content-Type': 'application/json',
    },    
}
```

result 부분을 간소화해서 다음과 같이 바꿔볼게요 

```javascript
const result = {
    ...postOption
}

console.log(result);
```
스프레드 연산자를 사용해서 postOption을 넣어줬는데요. `console.log(result)` 에는 다음과 같이 찍힙니다. 

```
{ 
  method: 'POST', 
  headers: { 'Content-Type': 'application/json'  } 
}
```

위에서 말씀드린대로 postOption의 모든 속성을 복사해서 result에 넣었습니다. 
이를 for loop로 변경하면 다음과 같습니다. 

```
const result = {};

// postOption 객체의 모든 속성을 result 객체로 복사
for (const key in postOption) {
    if (postOption.hasOwnProperty(key)) {
        result[key] = postOption[key];
    }
}
console.log(result);
```

특정 객체의 속성을 복사해서 넣는일은 매우 흔하기 때문에 매번 for loop를 사용하면 번거롭습니다. 
때문에 자바스크립트언어에서 이 기능을 연산자로 추가해서 간편하게 사용할 수 있도록 해주었습니다. 

이상입니다. 
도움이 되셨으면 좋겠습니다.
