### ISSUE TITLE
08장 NestJS 시작하기-의존성 주입 파트에서 @Injectable이 없는 부분이 있어요.

### ISSUE THREAD

**Issue by leeaain** [wapj/jsbackend#8]
330페이지의 제일 하단, blog.controller.ts 코드에는 `export class BlogContoller {` 위에 `@Injectable`이 없는데 원래 없는 건가요?
다른 파일에서 들은 다 붙이던데 여기만 안붙여서 궁금해서 여쭤봅니다. <br />
![IMG_1765](https://github.com/wapj/jsbackend/assets/141858855/0b0f1258-d434-40d6-b70c-7b1ae626302d)
![IMG_1766](https://github.com/wapj/jsbackend/assets/141858855/4182efd7-867c-425c-9815-767a3f4e4b27)

**Comment by ljt0815** [comment]
저도 지금 같은 부분을 보고 있어서 한번 답변 달아봅니다!
329쪽에 컨트롤러, 서비스, 리포지토리의 의존 관계 그림있는곳의 설명을 보시면
"블로그 예제에서는 [리포지토리와 서비스]를 다른 클래스에서 사용하므로 의존성 주입 대상이 될 겁니다"
"의존성 주입을 하는 방법은 주입하고 싶은 클래스에 @Injectable 데코레이터를 붙이기만 하면 됩니다."
그래서 리포지토리 파일과 서비스 파일에만 @Injectable을 붙이는 것 같습니다!

컨트롤러는 다른 클래스에서 사용하지 않기 때문에 생성자를 통해 객체를 생성할 필요 또한 없으므로 @Injectable을 붙이지 않는 것 같습니다!

**Comment by wapj** [comment]
@ljt0815 님이 해주신 말씀이 맞습니다. 
`@Injectable` 데코레이터가 있는 클래스나 메서드는 다른곳에 주입할 수 있다는 것으로 사용하는 것입니다. 
Controller 클래스는 다른곳에 주입해서 사용하지 않으므로 프로바이더가 아닙니다. 
따라서 `@Injectable`이 필요없는 것입니다. 

@ljt0815 님 감사합니다.
